python run_benchmark.py  --config-name=benchmark_libero_new \
            --multirun agents=bc_mamba_dec \
            agent_name=bc_mamba_dec \
            task_suite=libero_spatial,libero_object \
            wandb.project=mail \
            group=bc_mamba_dec \
            obs_seq=1,5 \
            n_layers=16 \
            mamba_ssm_cfg.d_state=16 \
            mamba_ssm_cfg.d_conv=4 \
            seed=0,1,2